velespi/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from places.views import (
    index, detail, new_place, new_media, new_review,
    like_place
)
from profiles.views import register, login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index),
    url(r'^register$', register, name="register"),
    url(r'^login$', login, name="login"),
    url(r'^logout$', logout, name="logout"),
    url(r'^places/(?P<id>\d+)$', detail, name='place_detail'),
    url(r'^places/(?P<place_id>\d+)/new-media$', new_media, name='new_media'),
    url(r'^places/(?P<place_id>\d+)/new-review$', new_review, name='new_review'),
    url(r'^places/(?P<place_id>\d+)/like$', like_place, name='like_place'),
    url(r'^new-place$', new_place, name="new_place"),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

places/models.py
from django.db import models
from django.conf import settings
from django.utils.encoding import smart_text


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return smart_text(self.name)

class PlaceManager(models.Manager):
    def get_queryset(self):
        qs = super(PlaceManager, self).get_queryset()
        return qs.filter(user__is_active=True)

    def active_places(self):
        return self.get_queryset().filter(
            is_active=True,
        )

class Place(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                             related_name='added_places')
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=False)
    coordinates = models.CharField(max_length=255, null=True, blank=False)
    category = models.ForeignKey(Category, blank=True, null=True)
    has_wifi = models.BooleanField(default=False)
    telephone = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True,
                                   related_name='liked_places')

    objects = PlaceManager()
    all_objects = models.Manager()

    def __str__(self):
        return smart_text(self.name)

    @models.permalink
    def get_absolute_url(self):
        return ('place_detail', (self.id,))

    def review_count(self):
        return self.review_set.count()

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    place = models.ForeignKey(Place)
    comment = models.TextField(null=True, blank=True)
    vote = models.IntegerField(
        default=3,
        choices=(
            (1, 'Berbat'),
            (2, 'Kötü'),
            (3, 'Meh'),
            (4, 'Uh'),
            (5, 'Yıkılıyor'),
        )
    )

    def __str__(self):
        return smart_text(self.comment)

class Media(models.Model):
    place = models.ForeignKey(Place)
    image = models.ImageField(upload_to="places")

    class Meta:
        verbose_name_plural = "Media"

    def __str__(self):
        return smart_text(self.image.url)

places/forms.py
from django.forms import (
	ModelForm, HiddenInput, ValidationError
)

from places.models import Place, Media, Review

class PlaceCreationForm(ModelForm):
	class Meta:
		model = Place
		fields = (
			'name',
			'coordinates',
			'category',
			'has_wifi',
			'telephone',
			'description',
		)
		widgets = {
			'coordinates': HiddenInput
		}

	def clean_coordinates(self):
		coords = self.cleaned_data['coordinates']

		try:
			lat, lng = coords.split(',')
			lat = float(lat)
			lng = float(lng)

			if (
				lat < -90 or lat > 90 or
				lng < -180 or lng > 180
			):
				raise ValidationError('Geçerli bir koordinat girin.')

		except ValueError:
			raise ValidationError('Koordinat girin.')

		return coords


class MediaCreationForm(ModelForm):
	class Meta:
		model = Media
		fields = ('image', )




class ReviewCreationForm(ModelForm):

	class Meta:
		
		model = Review
		fields = ( 'comment', 'vote',)

places/views.py
import json

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from places.models import Place
from places.forms import PlaceCreationForm, MediaCreationForm, ReviewCreationForm


def index(request):
    return render(
        request,
        'index.html',
        {
            'places': Place.objects.all(),
        }
    )

def detail(request, id):
    return render(
        request,
        'place.html',
        {
            'place': get_object_or_404(Place, id=id),
        }
    )

@login_required(login_url='login')
def new_place(request):
    form = PlaceCreationForm()

    if request.method == "POST":
        form = PlaceCreationForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.info(
                request,
                'Tebrikler. Yer bildiriminiz başarıyla alındı. '
                'Editör onayından geçtikten sonra yayınlanacaktır.'
            )
            return redirect('/')

    return render(
        request,
        'new_place.html',
        {
            'form': form,
        }
    )

@login_required(login_url='login')
def new_media(request, place_id):
    place = get_object_or_404(Place, id=place_id)
    form = MediaCreationForm()

    if request.method == "POST":
        form = MediaCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.place = place
            form.save()
            return redirect(place.get_absolute_url())

    return render(
        request,
        'new_media.html',
        {
            'place': place,
            'form': form,
        }
    )

@login_required(login_url='login')
def new_review(request, place_id):
    place = get_object_or_404(Place, id=place_id)
    form = ReviewCreationForm()

    if request.method == "POST":
        form = ReviewCreationForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.instance.place = place
            form.save()
            return redirect(place.get_absolute_url())

    return render(
        request,
        'new_review.html',
        {
            'place': place,
            'form': form,
        }
    )

@login_required(login_url='login')
def like_place(request, place_id):
    place = get_object_or_404(Place, id=place_id)

    if request.method == 'POST':
    
        if request.user in place.likes.all():
            place.likes.remove(request.user)
            action = 'unlike'
        else:
            place.likes.add(request.user)
            action = 'like'

        if request.is_ajax():
            return HttpResponse(
                json.dumps({
                    'count': place.likes.count(),
                    'action': action
                })
            )

    else:

        return HttpResponse(status_code=403)

    

    return redirect(place.get_absolute_url())

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Velespi{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
	<link rel="stylesheet" href="https://npmcdn.com/leaflet@0.7.7/dist/leaflet.css" />
</head>
<body>
<div class="container">
	{% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    {% endfor %}
	</ul>
	{% endif %}
	<header class="header">
		<div id="logo">
			<a href="/">velespi</a>
		</div>
		<div id="nav">
			<a href="/">Anasayfa</a>
			{% if user.is_authenticated %}
			<a href="{% url "new_place" %}">Yeni Yer Ekle</a>
			<a href="{% url "logout" %}">Çıkış yap ({{ user }})</a>
			{% else %}
			<a href="{% url "register" %}">Kayıt</a>
			<a href="{% url "login" %}">Giriş</a>
			{% endif %}
		</div>
	</header>
	<div class="content">
		{% block content %}
			PLACEHOLDER
		{% endblock %}
	</div>
	<footer class="footer">
		Linux Yaz Kampı 2016 - Django Sınıfı örnek projesidir.
	</footer>
</div>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://npmcdn.com/leaflet@0.7.7/dist/leaflet.js"></script>

{% block js %}
{% endblock %}

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

    <div id="map"></div>

{% endblock %}

{% block js %}
<script>
var map = L.map('map').setView([40.705601,31.678499], 12);
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
var markers = [];
{% for place in places %}
var marker = L.marker([{{ place.coordinates }}]).addTo(map)
    .bindPopup(
        '<a href="{{ place.get_absolute_url }}">' + 
        '{{ place.name }}' +
        '</a>'
    );
markers.push(marker);
{% endfor %}
var featureGroup = L.featureGroup(markers).addTo(map);
map.fitBounds(featureGroup.getBounds());
</script>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<h3>Login</h3>

<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Login" />
</form>
{% endblock %}

templates/new_media.html
{% extends "base.html" %}

{% block content %}
<h3>{{ place }} için yeni bir fotoğraf:</h3>

<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Ekle" />
</form>
{% endblock %}

templates/new_place.html
{% extends "base.html" %}

{% block content %}
<h3>Yeni Yer Bildirimi</h3>
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<div id="map" style="height: 300px"></div>
	<input type="submit" value="Gönder" />
</form>
{% endblock %}


{% block js %}
<script>
var map = L.map('map').setView([40.705601,31.678499], 12);
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
var marker;
map.on('click', function(e){
    if (marker) {
    	marker.setLatLng(e.latlng);
    } else {
    	marker = new L.marker(e.latlng).addTo(map);
    }
    var coordinates = e.latlng.lat + ", " + e.latlng.lng;
    document.getElementById('id_coordinates').value = coordinates;
});
</script>
{% endblock %}

templates/new_review.html
{% extends "base.html" %}

{% block content %}
<h3>{{ place }} için yeni bir yorum:</h3>

<form action="" method="post" >
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Ekle" />
</form>
{% endblock %}

templates/place.html
{% extends "base.html" %}

{% block content %}

    <h3>{{ place.name }}</h3>
    <p>
        <span id="like-count">{{ place.likes.count }}</span> kişi beğendi.

        {% if user in place.likes.all %}
        <a id="like" href="{% url "like_place" place.id %}">Beğenmekten vazgeç</a>
        {% else %}
        <a id="like" href="{% url "like_place" place.id %}">Beğen</a>
        {% endif %}
    </p>
    <div id="map"></div>
    <p>
        {{ place.description|linebreaksbr }}
    </p>
    {% if place.review_count > 0 %}
        <h3>Reviews</h3>
        {% for review in place.review_set.all %}
        <blockquote>
            {{ review.comment }} 
            ({{ review.vote }})
            <small>
                {{ review.user.username }}
            </small>
        </blockquote>
        {% endfor %}
    {% endif %}

    <h3>Fotoğraflar</h3>
    {% for media in place.media_set.all %}
        <img src="{{ media }}">
    {% empty %}
        <p>
            Bu yerin hiç fotoğrafı yok.
        </p>
    {% endfor %}

    <p>
        <a href="{% url "new_media" place.id %}">Fotoğraf ekle</a>
        <a href="{% url "new_review" place.id %}">Yorum ekle</a>
    </p>

{% endblock %}

{% block js %}
<script>
var map = L.map('map').setView([{{ place.coordinates }}], 12);
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
var marker = L.marker([{{ place.coordinates }}]).addTo(map)
    .bindPopup(
        '<a href="{{ place.get_absolute_url }}">' + 
        '{{ place.name }}' +
        '</a>'
    );
$('#like').on('click', function (event) {
    $.ajax({
        url: $("#like").attr('href'),
        method: 'POST',
        dataType: 'json',
        data: {
          csrfmiddlewaretoken: "{{ csrf_token }}"  
        }
    }).done(function (response) {
        $('#like-count').html(response.count);
        if (response.action === 'like') {
            $('#like').html('Beğenmekten vazgeç');
        } else {
            $('#like').html('Beğen');
        }
    });
    event.preventDefault();
});
</script>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}
<h3>Register</h3>

<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Register" />
</form>
{% endblock %}